name: CI

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    container: dimo414/ci-bash
    strategy:
      matrix:
        bash-version: [bash-5, bash-4, bash-3]
    steps:
      - uses: actions/checkout@v1
      - name: "Using ${{ matrix.bash-version }}"
        run: ${{ matrix.bash-version }} -c 'bats .'
    
  ShellCheck:
    runs-on: ubuntu-latest
    container: dimo414/ci-bash
    steps:
    - uses: actions/checkout@v1
    - name: ShellCheck
      run: |
        bash -c 'shopt -s globstar; shellcheck **/*.sh'
        bash bash-cache-dynamic-shellcheck.sh
