name: CI

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    container: dimo414/ci-bash
    strategy:
      matrix:
        bash-version: [bash-5, bash-4, bash-3]
    steps:
      - uses: actions/checkout@v1
      - name: "Using ${{ matrix.bash-version }}"
        run: ${{ matrix.bash-version }} -c 'bats .'
    
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: bash generate-dynamic.sh
    - name: ShellCheck
      uses: docker://koalaman/shellcheck-alpine
      with:
        entrypoint: sh
        args: -c "find . -name '*.sh' | xargs shellcheck"
    - uses: actions/upload-artifact@v1
      with:
        name: dynamic.sh
        path: dynamic.sh