name: CI

on: [push]

# TODO test against specific versions of Bash
jobs:
  Bash5:
    runs-on: ubuntu-latest
    container: dimo414/ci-bash
    steps:
      - uses: actions/checkout@v1
      - run: bash-5 -c 'bats .'

  ShellCheck:
    runs-on: ubuntu-latest
    container: dimo414/ci-bash
    steps:
    - uses: actions/checkout@v1
    - name: ShellCheck
      run: |
        bash -c 'shopt -s globstar; shellcheck **/*.sh'
        bash bash-cache-dynamic-shellcheck.sh
