name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    container: dimo414/ci-bash
    strategy:
      fail-fast: false
      matrix:
        # TODO bats 1.2.0 crashes with bash 4.2, upgrade and see if it can be enabled
        bash-version: [bash-5.2, bash-5.1, bash-5.0, bash-4.4, bash-3]
    steps:
      - uses: actions/checkout@v1
      - name: "Using ${{ matrix.bash-version }}"
        run: ${{ matrix.bash-version }} -c 'bats test'
      - name: "Benchmark"
        run: ${{ matrix.bash-version }} -c 'example() { sleep 1; } && source bash-cache.sh && bc::benchmark example && bc::benchmark_memoize example'
    
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: bash test/generate-dynamic.sh
    - name: ShellCheck
      uses: docker://koalaman/shellcheck-alpine
      with:
        entrypoint: sh
        args: -c "find . -name '*.sh' -exec shellcheck {} +"
    - uses: actions/upload-artifact@v2
      with:
        path: generated.sh
