name: CI

on: [push]

# TODO split BATS and ShellCheck into separate jobss
# TODO test against specific versions of Bash
jobs:
  ci:
    runs-on: ubuntu-latest
    container: dimo414/ci-bash

    steps:
    - uses: actions/checkout@v1
    - name: BATS
      run: bats .
    - name: ShellCheck
      run: |
        bash -c 'shopt -s globstar; shellcheck **/*.sh'
        bash bash-cache-dynamic-shellcheck.sh
